### ISSUE TITLE
"Window Match" picker for the "Window State" type is broken

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/ccsm#10]
This happens at least using the Window Rules and Animations plugins, and persists across CCSM restart and CCSM recompile. Haven't checked if it persists across reboots.

Compare the working "Window Type" picker type:

![screenshot_2016 08 28_07 55 01](https://cloud.githubusercontent.com/assets/10457522/18033501/05f8531e-6cf5-11e6-85a0-b7baac246cc1.png)

to the broken "Window State" picker:

![screenshot_2016 08 28_07 55 09](https://cloud.githubusercontent.com/assets/10457522/18033502/07bbddba-6cf5-11e6-88db-172fbff2636a.png)

**Comment by ShadowKyogre** [comment]
Heya. It looks like it's not automatically picking up your text color for use in the window state picker.

For further debugging help:
- What GTK3 Theme are you using?
- Which version of GTK3 are you using?

I'll go grab a screenshot ASAP of how it's supposed to render.

Also, regression implies that the window state picker used to work and/or existed before. When do you remember using it before this occurred?

On Aug 28, 2016, ethus3h <notifications@github.com> wrote:
>This happens at least using the Window Rules and Animations plugins,
>and persists across CCSM restart and CCSM recompile. Haven't checked if
>it persists across reboots.
>
>Compare the working "Window Type" picker type:
>
>![screenshot_2016 08 28_07 55
>01](https://cloud.githubusercontent.com/assets/10457522/18033501/05f8531e-6cf5-11e6-85a0-b7baac246cc1.png)
>
>to the broken "Window State" picker:
>
>![screenshot_2016 08 28_07 55
>09](https://cloud.githubusercontent.com/assets/10457522/18033502/07bbddba-6cf5-11e6-88db-172fbff2636a.png)

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by ShadowKyogre** [comment]
![2016-08-28-053903](https://cloud.githubusercontent.com/assets/673620/18033813/f8a4d880-6ce1-11e6-84ca-0543fa921d2f.png)

^this is after I use the picker on the dialog box.

Also, that's how the window state picker should look like. My best guess is that the theme file has an edge case I haven't found yet when picking up colors.

**Comment by ethus3h** [comment]
Hm, I just didn't remember there ever being a broken tool in the Window Match picker; I didn't know there was a new one ­— sorry for the confusion! I don't know what version of or theme for GTK3 I have installed (or how to figure it out, since it's not listed by `equery y gtk+`), but my ccsm is compiled using GTK2… (I only use GTK3 for the few apps that require it, and they look downright dreadful.)

**Comment by ShadowKyogre** [comment]
@ethus3h: It's all right xD. It happens to all of us.

Just the GTK2 theme then. It also works in GTK2 with my custom theme, but I do need more themes to work with to spot edge cases.

**Comment by ethus3h** [comment]
I'm using the Murrine GTK2 engine, with the MurrinaGilouche theme, customised using Gnome-Color-Chooser.

**Comment by ShadowKyogre** [comment]
@ethus3h : Thanks a bunch! I've reproduced the issue without the specific gnome-color-chooser customizations.

Here's the backtrace I got:
~~~~
/usr/lib/python3.5/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
Loading icons...
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ccm/Widgets.py", line 1281, in draw_event
    self.redraw ()
  File "/usr/lib/python3.5/site-packages/ccm/Widgets.py", line 1268, in redraw
    self.draw (cr, alloc.width, alloc.height)
  File "/usr/lib/python3.5/site-packages/ccm/Widgets.py", line 1226, in draw
    selBgColor = (bgColor.red * 1.2/65535.0, bgColor.green * 1.2/65535.0, bgColor.blue * 1.2/65535.0, 1)
AttributeError: 'tuple' object has no attribute 'red'
~~~~

I'll work on fixing this ASAP.

**Comment by ShadowKyogre** [comment]
@ethus3h : I found out what was going on. In the case of your theme, the colors were hardcoded without any variable labels.

You can see all the colors your theme is using with the script in here: http://lobais.blogspot.com/2006/07/system-colors-in-gtk.html

The way that script extracts the colors is agnostic of whether the colors are hard coded or not. That being said, a more foolproof solution will be rolling in soon!

**Comment by ethus3h** [comment]
Oh, wonderful, thank you! :)

**Comment by ShadowKyogre** [comment]
@ethus3h : You're welcome! I got the fixup code sitting in my desk. Just need to wait on upstream to deliver a fix for the gobject introspection wrapper not enumerating the colors (while the pygtk code enumerating the colors works fine).

See https://bugzilla.gnome.org/show_bug.cgi?id=770573 for more information.

**Comment by ethus3h** [comment]
Confirmed this is fixed. Thanks again! :)
