### ISSUE TITLE
Gtk2: Command keyboard shortcut labels have disappeared

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/ccsm#11]
The shortcuts seem to be having no effect.
![screenshot_2016 09 04_16 11 18](https://cloud.githubusercontent.com/assets/10457522/18233626/72ba5e1e-72ba-11e6-84cb-27428308ca53.png)

**Comment by ShadowKyogre** [comment]
@ethus3h : I've been seeing this happening on my own system when I fire up ccsm and navigate to any tab page for a plugin that has keybinding widgets on it.

It's a little bit tricky to reproduce, but here are the full steps I did to reproduce the missing labels bug:

1. Open CCSM
2. Navigate to any plugin
3. Click on a tab that has a keybinding widget ( eg: Commands -> Key Bindings OR General Options -> Key Bindings )
4. All the keybinding buttons should have blank labels. Their widths are equal to what should be with visible keybinding labels. This doesn't apply for values that're disabled, as they should just show "Disabled".

If you navigate to any other page besides the starting page or a non-keybinding page, this bug won't happen.

Can you verify that this same scenario reproduces the bug for you too reliably?

**Comment by ethus3h** [comment]
Happened again for me (I restarted Compiz in the mean time, FWIW) with Commands (tested twice), but not with General Options.

**Comment by ethus3h** [comment]
I wonder if this could be related to the profile corruption on updates that was being discussed in IRC…

**Comment by ShadowKyogre** [comment]
@ethus3h : I'm not sure if it is, but it could be.

BTW, could you show your ~/.config/compiz/compizconfig/Default.ini ?

**Comment by ethus3h** [comment]
Default.ini: https://gist.github.com/ethus3h/fdfd200b3d6078c525cdeab2eb65e9fb

**Comment by soreau** [comment]
@ShadowKyogre Did you know why this is happening?

**Comment by ethus3h** [comment]
This seems to be just a display bug that is fixed upon clicking one of the buttons missing a label. The keyboard shortcuts *do* seem to work regardless of the display issue.

**Comment by soreau** [comment]
If it does not happen while compiz is running but it is reproducible, then a bisect should be performed on ccsm.

**Comment by ethus3h** [comment]
I think I've found something: now that I'm using a high-DPI display, I can see the labels, but they're offset strangely. See the attached screenshot. In other words, it looks like the text is being drawn, but in the wrong place (but the buttons are the correct size). Hopefully this is useful...
[
![screenshot_2016 10 27_10 02 26](https://cloud.githubusercontent.com/assets/10457522/19770288/b8be6cb6-9c2c-11e6-8a4f-0801ef9b4cee.png)
](url)

**Comment by XRevan86** [comment]
f27f899 should handle that.

**Comment by ethus3h** [comment]
Ooh, haven't tested yet, but yay, thanks!
