### ISSUE TITLE
Bug Command Line with CCSM -> error with ccsm -c CATEGORY or ccsm -p PLUGIN

### ISSUE THREAD

**Issue by Equipe-ADVL** [compiz-reloaded/ccsm#19]
Hello,

Config -> Debian Jessie + Xfce 4.12

I report a bug when using CCMS 0.8.14 command line.
For example : ccsm -p mag or ccsm -p showmouse (ccsm -p PLUGIN -> see ccsm --help)
no longer work. I get an error. The plugin as argument is not recognized.
(Same bug with ccsm -c CATEGORY).
With version 0.8.12, it worked without any problem...

An idea ?

**Comment by soreau** [comment]
Can you possibly bisect?

**Comment by Equipe-ADVL** [comment]
Config -> Debian Jessie + Xfce 4.12

I report a bug when using CCMS 0.8.14 command line.
For example : this command line : ccsm -p showmouse (ccsm -p PLUGIN -> see ccsm --help)
no longer work. I get an error. The plugin as argument is not recognized.

With version 0.8.12, it worked without any problem...
