### ISSUE TITLE
Fails to open when packages are rebuilt on Debian testing (buster)

### ISSUE THREAD

**Issue by stevenpusser** [compiz-reloaded/ccsm#21]
I get a reported error:

`$ ccsm
Traceback (most recent call last):
  File "/usr/bin/ccsm", line 36, in <module>
    import compizconfig
ImportError: /usr/lib/python2.7/dist-packages/compizconfig.x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf`

Seems to be related to this: https://stackoverflow.com/questions/47251562/how-to-fix-undefined-symbol-pyfpe-jbuf

and the Debian changelog shows that the fpectl extension was dropped from Debian testing's Python a few months ago.

**Comment by XRevan86** [comment]
You should contact @elgeneralmidi for that.

**Comment by XRevan86** [comment]
Though I see you took matters into your own hands and created [home:stevenpusser:compiz-reloaded](https://build.opensuse.org/project/show/home:stevenpusser:compiz-reloaded) on openSUSE Build Server :-).

**Comment by XRevan86** [comment]
@stevenpusser, @elgeneralmidi contacted us and told that he no longer works on the Debian repository, so that's pretty much a WONTFIX.
He is also willing to give the tuxfamily subdomain to someone who is willing to maintain the repository.

**Comment by stevenpusser** [comment]
Thanks....but I'm pretty happy with the repo on the OBS, as long as they
don't vanish on me.  I have reports that rebuilding the source packages
from the tuxfamily repo on the OBS for Buster solved the issue for those
users.
