### ISSUE TITLE
random python issue preventing ccsm from launching

### ISSUE THREAD

**Issue by stormchaser3000** [compiz-reloaded/ccsm#4]
ich python2) PYTHONPATH=$prefix/lib/python2.7/site-packages/ ccsm
Traceback (most recent call last):
  File "/usr/local/bin/ccsm", line 30, in <module>
    import gi
  File "/lib/python2.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/python2.7/site-packages/gi/_gi.so: undefined symbol: _Py_ZeroStruct

**Comment by XRevan86** [comment]
Problem happens when importing gi module, so issue must be happening not in CCSM but inside PyGObject3 built in your GNU/Linux distribution.
