### ISSUE TITLE
[XFCE4 Debian] ccsm Gtk error with compiz 0.8.12.3

### ISSUE THREAD

**Issue by dt060** [compiz-reloaded/ccsm#8]
Hello,

I installed compiz following the [Compiz Debian](http://compiz-debian.tuxfamily.org/) instructions and am able to run compiz fine, including emerald and the compiz icon. 

However, when trying to configure compiz using ccsm, the settings manager does not start. When running ccsm in a terminal, I get the following error:

dan@debian:~$ ccsm 
Traceback (most recent call last):
  File "/usr/bin/ccsm", line 33, in <module>
    gi.require_version('Gtk', '2.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 104, in require_version
    (namespace, version))
ValueError: Namespace Gtk not available for version 2.0

What can I do/try to fix this?

Cheers,
Dan

**Comment by soreau** [comment]
Sounds like you might be missing a dependency. Do you have libgtk2.0-dev installed?

**Comment by XRevan86** [comment]
You really don't have ```gir1.2-gtk-2.0``` installed.
